default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: jeanette_development

test:
  <<: *default
  database: jeanette_test

production:
  <<: *default
  database: jeanette_production
  username: jeaentte
  password: <%= ENV['EXAMPLE_DATABASE_PASSWORD'] %>
